name: Auto Merge on PR Approval and Tests Pass

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:PR_MERGE_BRANCH
          git checkout PR_MERGE_BRANCH

      - name: Install dependencies and run tests
        run: |
          # Add commands to install dependencies and run tests
          # For example:
          # mvn clean test

      - name: Auto merge if tests pass and PR is approved
        if: github.event_name == 'pull_request' && github.event.action == 'synchronize' && github.event.pull_request.labels[0].name == 'tests-passed' && github.event.pull_request.review.approvals >= 1
        run: |
          # Merge the PR
          git pull origin PR_MERGE_BRANCH
          git merge --no-ff origin/${{ github.event.pull_request.head.ref }}
          git push origin PR_MERGE_BRANCH